spring:
  #数据库配置信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jxgl
    username: root
    password: 199550
  #配置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  configuration:
    logimpl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云属性定义
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret: 
    bucketName:
